# Path to your oh-my-zsh installation.
  export ZSH=/home/paul/.oh-my-zsh

ZSH_THEME="fishy"
DISABLE_AUTO_UPDATE="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="yyyy-mm-dd"
plugins=(git vi-mode docker docker-compose lein)

# User configuration

  export PATH="/opt/scala/bin:/opt/maven/bin:/opt/ant/bin:/opt/go/bin:/opt/node/bin:/opt/activator:/opt/gradle/bin:/opt/sbt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/paul/.rvm/bin"

source $ZSH/oh-my-zsh.sh
export EDITOR=vim

export SSH_KEY_PATH="~/.ssh/rsa_id"

eval `keychain -q --eval --agents ssh id_rsa`
unalias gg
